name: Daily Commit Workflow
on:
  schedule:
    - cron: '30 0 * * *' # Runs daily at 12:30 AM UTC
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  daily_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update file by 21f3000037@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date)" >> daily_update.txt

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add daily_update.txt
          git commit -m "Daily automated commit at $(date)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
