name: Daily Commit

on:
  schedule:
    - cron: '00 5 * * *'
  workflow_dispatch:

jobs:
  commit_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Modify timestamp file - 21f3000037@ds.study.iitm.ac.in
        run: echo "Last run: $(date -u)" > last_run.txt

      - name: Commit changes
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Action Bot"
          git add last_run.txt
          git commit -m "Daily commit: $(date -u)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.testy }}@github.com/${{ github.repository }} HEAD:main
